Kaab 122 color
Mecuate/bees pull request #4
Opened 2023-09-21 20:46 UTC by Yoshigei

asignaciones de color

2023-09-22 00:21 UTC, thetoxicguy approved these changes
I have checked this along with Yoshi

2023-09-22 04:45 UTC, ChicomeMX7 commented
@Yoshigei OK, hay que tener cuidado con el formato usado en el repositorio, habia algunos caracteres de mas en algunas partes del codigo, pero como estaba dessincronizado marcaba muchos cambios que no existian en realidad dentro del branch target dev, ahora ya solo marca 8 camios. (Y)

2023-09-22 04:50 UTC, ChicomeMX7 requested changes

2023-09-22 04:50 UTC, ChicomeMX7 commented on src/components/TextEditor/TextEditor.styles.ts
> +    background: '#ffffff',
Este color si debe ser desde una constante definida en otro modulo.

2023-09-22 04:50 UTC, ChicomeMX7 commented on src/screens/Dashboard/Dashboard.styles.ts
>  // 1740 - (1110 +350+270)
fix, quitar estas notas

2023-09-22 04:50 UTC, ChicomeMX7 commented on src/styles/colors.ts
> +        [800]: '#191C1B', // TODO: cambiar colores
creo que se puede limpiar el codigo quitando este TODO.

2023-09-22 04:50 UTC, ChicomeMX7 commented on src/styles/colors.ts
> +//
remover este comentario del codigo.

2023-09-23 03:47 UTC, Yoshigei commented on src/components/TextEditor/TextEditor.styles.ts
> +    background: '#ffffff',
listo. la referencia está tomada de colors

2023-09-23 03:49 UTC, Yoshigei commented on src/screens/Dashboard/Dashboard.styles.ts
>  // 1740 - (1110 +350+270)
listo.

2023-09-23 03:49 UTC, Yoshigei commented on src/styles/colors.ts
> +        [800]: '#191C1B', // TODO: cambiar colores
corregido

2023-09-23 03:50 UTC, Yoshigei commented on src/styles/colors.ts
> +//
removido

2023-09-25 05:29 UTC, ChicomeMX7 approved these changes

2023-09-25 05:31 UTC, merged